databases:
  - name: product-importer-db
    databaseName: product_importer
    user: product_importer_user

services:
  - type: web
    name: product-importer
    env: python
    buildCommand: "pip install -r requirements-render.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn product_importer.wsgi:application --timeout 3600 --workers 1 --max-requests 50 --max-requests-jitter 5 --preload --worker-class sync --worker-tmp-dir /dev/shm --keep-alive 5"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: product-importer-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 1
    healthCheckPath: /health/

  - type: worker
    name: product-importer-worker
    env: python
    buildCommand: "pip install -r requirements-render.txt"
    startCommand: "celery -A product_importer worker --loglevel=info --concurrency=1 --max-tasks-per-child=5 --pool solo"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: product-importer-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        fromService:
          name: product-importer-redis
          property: connectionString

  - type: redis
    name: product-importer-redis
    plan: free